data_name: PCBA
seed: 0

num_scale: 1
scales: [0.25, 0.5, 0.75, 1]
#scales: [2,4,8,16]
tolerance: 0.0000001
approximation_order: 3
pos_weight: 1

num_layer: 3
hidden_dims: [8,16,32]
latent_dim: 20

device: cuda:1
device_ids: "1"
lr: 0.0005
num_epoch: 100
batch_size: 32

#### lighting and wandb config ###
precision: highest
output_dir: /cm/shared/khangnn4/WavePE
wandb_project: WavePE
num_ckpts: 3
save_every_n_epochs: 1
#ckpt_path: /cm/shared/khangnn4/WavePE/ckpts/PCBA_small_resolution/PCBA_epoch=77_train_loss=0.267_val_loss=0.277_val_best_loss=0.277.ckpt 
ckpt_path: 
version: debug_1


### 
debug: True